### ISSUE TITLE
automatic reconnect if tcp socket goes down

### ISSUE THREAD

**Issue by mcollina** [jsumners/pino-socket#3]
We should also be able to specify a "sliding window" of data we can buffer up when there is no connection.

cc @davidmarkclements

**Comment by jsumners** [comment]
I can see the benefit. But then you get into the discussion in https://github.com/mcollina/pino/issues/41. The question is really, is it better to drop logs or potentially send incomplete log "lines"?

Hmmm, having written that it occurs to me that since `pino-socket` already expects to receive a LF as a delimiter before forwarding. So that could be used to stick the chunks into a fixed length FIFO buffer.

As for the actual issue of automatic reconnect. In the default mode, UDP, this shouldn't be an issue; it's just throwing packets out into the ether and whatever happens, happens.

**Comment by mcollina** [comment]
So, this is just for TCP. I think we should just skip the lines while the connection went down for now. The problem with current setup is that pino-socket would crash the upstream process if the connection goes down.

**Comment by jsumners** [comment]
I have an idea on solving the tcp reconnect issue. I'll be working on it soon.

**Comment by jsumners** [comment]
Okay, I've implemented some sort of tcp reconnecting on the `develop` branch. Please give it a review and test it in your situation. I'm fairly certain it needs more work before a release.

**Comment by mcollina** [comment]
👍 , I'll test on Monday.

**Comment by mcollina** [comment]
It does what's advertised :)

**Comment by jsumners** [comment]
Did you have any issues with shutting down the local process?

**Comment by jsumners** [comment]
~shrug~ If so it can be fixed in 0.4.1 or 0.5.0. The reconnect feature is now published in 0.4.0.

**Comment by mcollina** [comment]
@jsumners I didn't, is that an issue? which version of node?

**Comment by jsumners** [comment]
It was just something I experienced during a local test. It was most likely a fault of mine.
